#!/bin/bash

# Run conv and cconv, compare against analytic result.

start=6
stop=20

if [ "$1" = "" ]; then
    echo Usage: $0 "["conv\|cconv"]" "["start"]" "["stop"]"
    exit
fi

divisor=0;

if [ "$1" = "conv" ]; then
    shift=1;
    offset=2;
    divisor=3;
    outdir=timings1r
fi
if [ "$1" = "cconv" ]; then
    outdir=timings1c
fi

if [ "$outdir" = "" ]; then
    echo "not implemented"
    exit
fi

mkdir -p $outdir
cd $outdir
rm -f error.explicit error.implicit
cd ..

if [ "$2" != "" ]; then
    start=$2
fi

if [ "$3" != "" ]; then
    stop=$3
fi

if [ "$BASH_VERSION" = "" ]; then
    #  Ubuntu used dash, which messes up "echo -e"
    EOPTS=""
else
    # we are using bash.
    EOPTS="-e"
fi

echo Calculating error:
i=$start;
while (test $i -le $stop); do
    echo -n $i" "
    m=$( echo 2^$i | bc)
    echo $EOPTS  "$m \t $(nice -n 19 ./$1 -i -N1 -t -m $m | grep error | sed s/error=//)"| cat >> $outdir/error.implicit
    if [ "$divisor" != "0" ]; then
	m=$( echo \(2^\($i+$shift\)+$offset\)/$divisor | bc)
    fi
    echo $EOPTS  "$m \t $(nice -n 19 ./$1 -e -N1 -t -m $m | grep error | sed s/error=//)" | cat >> $outdir/error.explicit
    i=$((i+1))
done
echo

exit 0
